import Papa from 'papaparse';
import { calculateVatReport, type RawTransaction, type ClassifiedTransaction, type VatReport } from '../lib/vatEngine.js';
import { genereerStabielTransactieId } from '../lib/btwEngine.js';

/** @deprecated Legacy compatibility utility. Production VAT flows use vatCsvParser + btwEngineSafe. */
export { calculateVatReport, type RawTransaction, type ClassifiedTransaction, type VatReport };

export interface VatResultSummaryMetrics { totalRowsProcessed:number; highConfidenceCount:number; mediumConfidenceCount:number; lowConfidenceCount:number; uncertainCount:number; excludedCount:number; categoryCounts:Record<'A'|'B'|'C'|'D'|'E'|'F'|'G',number>; rubriekTotals:Record<string,number>; provisionalNetVat:number; conservativeNetVat:number; marginOfError:number; disclaimer:string; }
export interface VatResult { inc21:number; ex21:number; inc9:number; ex9:number; vat21:number; vat9:number; rubriek4a_vat:number; rubriek4b_vat:number; rubriek5b_vat:number; deductibleInputVat21:number; deductibleInputVat9:number; totalVatToPay:number; netVatToPayOrClaim:number; vatReport:VatReport; metrics:VatResultSummaryMetrics; }
export type TransactionType='INKOMST'|'UITGAVE'|'CREDIT_CORRECTIE'; export type ConfidenceLevel='HOOG'|'MIDDEL'|'LAAG'; export type VatCategory='A'|'B'|'C'|'D'|'E'|'F'|'G';
export interface TransactionDetail { description:string; counterparty?:string; iban?:string; mededelingen?:string; amount:number; isIncome:boolean; transactionType:TransactionType; appliedRate:number|null; rubriek:string; vatCategory:VatCategory; categoryLabel:string; confidence:ConfidenceLevel; reasoningPath:string; matchedRule:string; candidateRate?:number|null; candidateCategory?:VatCategory|null; candidateReason?:string; isReverseCharged?:boolean; isBuaHoreca?:boolean; isExemptArt11?:boolean; isOutlier?:boolean; }
const round2=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
export const MANDATORY_DISCLAIMER="Dit is een geautomatiseerde inschatting op basis van bankregel-omschrijvingen, geen fiscaal advies. Controleer alle ONZEKER-regels en een steekproef van de HOOG-confidence regels met de onderliggende facturen of een boekhouder voordat u aangifte doet.";
export const classifyVatTransaction=(description:string,tegenrekening:string,mededelingen:string,isIncome:boolean,amount:number)=>{const desc=description.toLowerCase().trim();const iban=tegenrekening.replace(/\s/g,"").toUpperCase();const notes=mededelingen.toLowerCase().trim();const fullText=`${desc} ${notes}`;const match=(text:string,kw:string)=>kw.length<=4?new RegExp(`\\b${kw}\\b`,'i').test(text):text.includes(kw);const horeca=["restaurant","cafe","café","brasserie","lunchroom","eetcafe","eetcafé","bar","bistro","hotel","pension","grand café","grandcafe","horeca","ter plekke","ter plaatse","horeca-exploitant","horeca-consumptie"];const meals=["lunch","diner","ontbijt","consumptie","klantlunch","zakelijke lunch","eten en drinken"];const food=["boodschappen","koffie","pantry-artikel","pantry-artikelen","pantry","supermarktaankopen","voeding","eetwaren","brood","groente","fruit","vlees","vis","supermarkt","lidl","albert heijn","jumbo","aldi","plus supermarkt","plusmarkt","coop"];const transport=["trein","bus","taxi","ov","openbaar vervoer","ov-chipkaart","ns","gvb","ret","htm","arriva","transdev"];const books=["boeken","tijdschrift","tijdschriften","krant","abonnement krant","geneesmiddelen","logies","hotel","pension","camping","overnachting"];const telecom=["telecom","telecommunicatie","internet","telefonie","mobiel","glasvezel","tv abonnement","televisie","bellen","databundel","telefoonabonnement","internetabonnement","telecomdiensten","provider"];const services=["hosting","software","ontwikkeling","development","webdesign","seo","cms","applicatie","dashboard","api","reparatie","onderhoud","advies","content","front-end","back-end","koppeling","engine","consultancy","portaal","licentie","saas","cloud",...telecom];const physical=["bureaustoel","monitor","kabels","ssd","kantoorartikelen","kantoorbenodigdheden","kantoorbenodigdheid","kantoormateriaal","brandstof","postzegel","postzegels","pakketzegel","pakketzegels","schoonmaak","gereedschap","hardware","pakket","verzending","vrachtgoederen","douane","invoer","levering goederen"];const r=(rate:number|null,rubriek:string,category:VatCategory,label:string,confidence:ConfidenceLevel,reason:string,reverse=false,bua=false,exempt=false)=>({category,categoryLabel:label,rate,rubriek,confidence,reasoningPath:reason,candidateRate:rate,candidateCategory:category,isReverseCharged:reverse,isBuaHoreca:bua,isExemptArt11:exempt});
if(amount<0||["creditnota","credit-nota","credit nota","storno","terugbetaling","retour","restitutie","refund"].some(k=>match(notes,k)))return r(21,isIncome?'1a':'5b','G','Credit-/stornotransactie','HOOG',"Creditnota/terugbetaling gedetecteerd.");
if(["spaarrekening","interne overboeking","eigen rekening","kruisposten","storting eigen vermogen","opname","salaris","loon","pensioenpremie","pensioen","aflossing lening","aflossing","rente lening","kapitaalstorting"].some(k=>match(fullText,k))||(["belastingdienst","btw afdracht","inkomstenbelasting","voorlopige aanslag","loonheffing afdracht","loonheffing"].some(k=>match(fullText,k))&&!isIncome))return r(0,'GEEN_BTW','A','Niet-BTW-relevante mutatie','HOOG',"Niet-BTW-relevante mutatie.");
const gov=["kvk","rdw","gemeente","omgevingsdienst","kadaster"].some(k=>match(desc,k)||match(notes,k));if(gov)return r(0,'0','B','Buiten reikwijdte (overheidstaken)','HOOG',"Overheidstaak buiten reikwijdte.");
if(["arts","tandarts","fysiotherapie","verpleging","zorginstelling","ziekenhuis","onderwijs","cursus","opleiding","school","universiteit","erkende opleiding","bankkosten","pakketkosten bank","provisie bank","hypotheekrente","verzekeringspremie","verzekering","huur kantoor","huur woning","pacht"].some(k=>match(fullText,k)))return r(0,'0','B','Vrijgesteld (art. 11 Wet OB)','HOOG',"Vrijgestelde prestatie.",false,false,true);
const country=iban.substring(0,2),foreign=/^[A-Z]{2}$/.test(country)&&country!=="NL";if(foreign&&!isIncome){const goods=["pakket","verzending","hardware","douane","invoer","vrachtgoederen","levering goederen"].some(k=>match(fullText,k));return r(goods?21:21,goods?'4a':'4b',goods?'D':'C',goods?'Grensoverschrijdend — Goederen':'Grensoverschrijdend — Dienst (BTW verlegd 4b)','HOOG',`Buitenlandse transactie (${country}).`,true,false,false);}if(foreign&&isIncome)return r(null,'3b','C','Grensoverschrijdend — Uitgaande verkopen','LAAG',`Buitenlandse uitgaande transactie (${country}) vereist factuurcontrole.`);
if(["gemengde factuur","lunch en software","boeken en kantoorartikelen","splitsing vereist"].some(k=>match(fullText,k)))return r(null,'1a','F','Gemengde factuur','LAAG','Gemengde factuur vereist handmatige splitsing.');
const horecaHit=horeca.some(k=>match(desc,k)||match(notes,k)),mealHit=meals.some(k=>match(notes,k)||match(desc,k));if(horecaHit&&mealHit)return r(9,'1b','E','Horeca consumptie (BUA)','HOOG','Horeca-consumptie; BTW niet aftrekbaar.',false,true,false);
if(telecom.some(k=>match(desc,k)||match(notes,k)))return r(21,'1a','E','Telecommunicatie (21%)','HOOG','Telecommunicatiedienst.');
if(services.some(k=>match(desc,k)||match(notes,k)))return r(21,'1a','E','Binnenlandse dienst (21%)','HOOG','Dienstverlening tegen 21%.');
if(physical.some(k=>match(desc,k)||match(notes,k)))return r(21,'1a','E','Zakelijke uitgave (21%)','HOOG','Zakelijke uitgave tegen 21%.');
if(food.some(k=>match(desc,k)||match(notes,k))||meals.some(k=>match(notes,k)))return r(9,'1b','E','Levensmiddelen (9%)','HOOG','Levensmiddelen tegen 9%.');
if(transport.some(k=>match(notes,k)))return r(9,'1b','E','Personenvervoer (9%)','HOOG','Personenvervoer tegen 9%.');
if(books.some(k=>match(notes,k)))return r(9,'1b','E','Boeken / Logies (9%)','HOOG','Boeken/logies tegen 9%.');
if(["margeregeling","tweedehands","gebruikte goederen"].some(k=>match(fullText,k)))return r(null,'1e','E','Margeregeling (art. 28b)','LAAG','Mogelijke margeregeling; handmatige controle vereist.');
return r(null,isIncome?'1a':'5b','E','Onzekere classificatie','LAAG','Onvoldoende informatie voor automatische fiscale classificatie.');};
export function calculateOutliers(amounts:number[]){if(!amounts.length)return{median:0,iqr:0,p90:0};const s=[...amounts].sort((a,b)=>a-b),n=s.length,p=(x:number)=>{const i=(n-1)*x,l=Math.floor(i),u=Math.ceil(i);return l===u?s[l]:s[l]+(s[u]-s[l])*(i-l)};const median=p(.5),q1=p(.25),q3=p(.75);return{median,iqr:q3-q1,p90:p(.9)}}
export const processCSVForVAT=(csvContent:string|File):Promise<{results:VatResult;details:TransactionDetail[]}>=>(async()=>{const text=typeof csvContent==='string'?csvContent:await csvContent.text();const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)throw new Error('Bestand is leeg');const parsed=Papa.parse<string[]>(text,{delimiter:lines[0].split(';').length>=lines[0].split(',').length?';':',',header:false,skipEmptyLines:true});const rows=parsed.data;if(rows.length<2)throw new Error('Geen gegevens gevonden in het bestand.');const h=rows[0].map(x=>String(x).trim());const expected=["Datum","Naam / Omschrijving","Rekening","Tegenrekening","Code","Af Bij","Bedrag (EUR)","Mutatiesoort","Mededelingen"];for(const e of expected)if(!h.includes(e))throw new Error(`Ontbrekende verplichte kolom: ${e}`);const idx=(name:string)=>h.indexOf(name),details:TransactionDetail[]=[],raw:RawTransaction[]=[];for(let i=1;i<rows.length;i++){const row=rows[i];if(!row||row.length<expected.length)continue;const date=String(row[idx('Datum')]??'').trim();if(!/^\d{8}$/.test(date)&&Number.isNaN(Date.parse(date)))throw new Error(`Ongeldige datum gedetecteerd: ${date}`);const rawAmount=String(row[idx('Bedrag (EUR)')]??'').trim();const clean=rawAmount.replace('€','').replace(/\s/g,'').replace(/\./g,'').replace(',','.');const amount=Math.abs(Number(clean));if(!Number.isFinite(amount))throw new Error(`Ongeldig transactiebedrag gedetecteerd: ${rawAmount}`);if(amount===0)continue;const desc=String(row[idx('Naam / Omschrijving')]??'').trim(),iban=String(row[idx('Tegenrekening')]??'').trim(),memo=String(row[idx('Mededelingen')]??'').trim(),direction=String(row[idx('Af Bij')]??'').trim().toLowerCase(),income=['bij','income','inkomsten','c','cr'].includes(direction);const id=`tx_${i}`;const c=classifyVatTransaction(desc,iban,memo,income,amount);raw.push({id,description:desc,amount_incl:amount,type:income?'income':'expense',memo: memo||undefined,tegenrekening_iban:iban||undefined});details.push({description:desc,counterparty:desc,iban,mededelingen:memo,amount,isIncome:income,transactionType:income?'INKOMST':'UITGAVE',appliedRate:c.rate,rubriek:c.rubriek,vatCategory:c.category,categoryLabel:c.categoryLabel,confidence:c.confidence,reasoningPath:c.reasoningPath,matchedRule:c.reasoningPath,candidateRate:c.candidateRate,candidateCategory:c.candidateCategory,isReverseCharged:c.isReverseCharged,isBuaHoreca:c.isBuaHoreca,isExemptArt11:c.isExemptArt11});}
const vr=calculateVatReport(raw);const trusted=details.filter(d=>d.appliedRate!==null);const vatToPay=vr.overzicht.verschuldigd.totaal,vatClaim=vr.overzicht.aftrekbaar.totaal;return{results:{inc21:trusted.filter(d=>d.isIncome&&d.appliedRate===21).reduce((s,d)=>s+d.amount,0),ex21:0,inc9:trusted.filter(d=>d.isIncome&&d.appliedRate===9).reduce((s,d)=>s+d.amount,0),ex9:0,vat21:vr.overzicht.verschuldigd.inkomsten_21,vat9:vr.overzicht.verschuldigd.inkomsten_9,rubriek4a_vat:0,rubriek4b_vat:vr.overzicht.verschuldigd.verlegde_btw,rubriek5b_vat:vatClaim,deductibleInputVat21:vr.overzicht.aftrekbaar.uitgaven_21,deductibleInputVat9:vr.overzicht.aftrekbaar.uitgaven_9,totalVatToPay:vatToPay,netVatToPayOrClaim:vatToPay-vatClaim,vatReport:vr,metrics:{totalRowsProcessed:details.length,highConfidenceCount:details.filter(d=>d.confidence==='HOOG').length,mediumConfidenceCount:details.filter(d=>d.confidence==='MIDDEL').length,lowConfidenceCount:details.filter(d=>d.confidence==='LAAG').length,uncertainCount:details.filter(d=>d.appliedRate===null).length,excludedCount:0,categoryCounts:{A:0,B:0,C:0,D:0,E:0,F:0,G:0},rubriekTotals:{},provisionalNetVat:vatToPay-vatClaim,conservativeNetVat:vatToPay-vatClaim,marginOfError:0,disclaimer:MANDATORY_DISCLAIMER}},details}})();
export function parseCsvToRawTransactions(csvContent:string):RawTransaction[]{const str=csvContent.replace(/^\uFEFF/,'').trim();if(!str)return[];const parsed=Papa.parse<string[]>(str,{delimiter:(str.match(/;/g)||[]).length>=(str.match(/,/g)||[]).length?';':',',header:false,skipEmptyLines:true});const rows=parsed.data;if(!rows||rows.length<=1)return[];const headers=rows[0].map(h=>String(h).trim().toLowerCase());const find=(ks:string[])=>ks.map(k=>headers.findIndex(h=>h.includes(k))).find(i=>i!==-1)??-1;const di=find(['datum','date']),oi=find(['naam / omschrijving','omschrijving','naam','description','counterparty']),ti=find(['tegenrekening','iban']),ai=find(['af bij','af/bij','type','direction']),bi=find(['bedrag','amount']),mi=find(['mededelingen','memo','opmerking','notes']);const out:RawTransaction[]=[];for(let i=1;i<rows.length;i++){const row=rows[i];if(!row||!row.length)continue;const d=di>=0?String(row[di]??'').trim():'';const desc=oi>=0?String(row[oi]??'').trim():'Transactie';const iban=ti>=0?String(row[ti]??'').trim():'';const dir=ai>=0?String(row[ai]??'').trim().toLowerCase():'';const raw=bi>=0?String(row[bi]??'').trim():'0';const n=Number(raw.replace('€','').replace(/\s/g,'').replace(/\./g,'').replace(',','.'));if(!Number.isFinite(n))throw new Error(`Ongeldig bedrag op CSV-regel ${i+1}: ${raw}`);const income=['bij','income','inkomsten','c','cr'].includes(dir)?true:['af','expense','uitgaven','d','dr'].includes(dir)?false:n>0;const amount=Math.abs(n);if(amount===0)continue;out.push({id:genereerStabielTransactieId({date:d,description:desc,amount_incl:amount,tegenrekening_iban:iban||undefined}),date:d,description:desc,amount_incl:amount,type:income?'income':'expense',memo:(mi>=0?String(row[mi]??'').trim():'')||undefined,tegenrekening_iban:iban||undefined});}return out;}
